/**
 * Write back a risk score comment to a Jira issue.
 * Called after RiskScoreComputed for releases that have a jira_version_id.
 *
 * Auth: OAuth2 per-tenant token (stored in DB — looked up by tenant_id).
 * For MVP: uses basic auth or a static PAT stored in env.
 */
import logger from '../logger.js';

const LEVEL_EMOJI = { SAFE: '✅', AT_RISK: '⚠️', BLOCKED: '🚨' };

/**
 * @param {string} jiraBaseUrl   e.g. https://your-org.atlassian.net
 * @param {string} issueId       Jira issue key (e.g. PROJ-123)
 * @param {object} event         RiskScoreComputed payload
 * @param {string} accessToken   OAuth2 bearer token for this tenant
 */
export async function writeJiraComment(jiraBaseUrl, issueId, event, accessToken) {
  if (!jiraBaseUrl || !issueId || !accessToken) {
    logger.debug({ msg: 'jira_comment_skipped', reason: 'missing config', release_id: event.release_id });
    return;
  }

  const emoji   = LEVEL_EMOJI[event.level] ?? '•';
  const reasons = (event.reasons ?? [])
    .map((r) => `* *${r.window_name}* — +${r.points} pts`)
    .join('\n');

  const body = `${emoji} *Regulatory Risk Assessment — ${event.level} (${event.score}/100)*

Release: *${event.release_name ?? event.release_id}*
Planned date: ${event.planned_date}
Risk score: ${event.score}/100

${reasons ? `*Contributing factors:*\n${reasons}` : '_No regulatory windows impacted this release._'}

_Generated by Regulated Release Calendar_`;

  const url = `${jiraBaseUrl}/rest/api/2/issue/${issueId}/comment`;

  try {
    const res = await fetch(url, {
      method:  'POST',
      headers: {
        'Content-Type':  'application/json',
        'Authorization': `Bearer ${accessToken}`,
      },
      body: JSON.stringify({ body }),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      logger.error({ msg: 'jira_comment_failed', status: res.status, issue: issueId, body: text.slice(0, 200) });
    } else {
      logger.info({ msg: 'jira_comment_written', issue: issueId, release_id: event.release_id });
    }
  } catch (err) {
    logger.error({ msg: 'jira_comment_error', error: err.message, issue: issueId });
  }
}
